### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by yoursbh** [lagerfeuer/cryptocompare#1]
An error occurs when install the package by pip 

> $ pip install cryptocompare
> 
> Collecting cryptocompare
>   Using cached cryptocompare-0.3.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/hc/jf7tmyyn3fq_8d7l7m_fm09c0000gn/T/pip-build-s3mE1w/cryptocompare/setup.py", line 3, in <module>
>         with open('README.rst', encoding="utf-8") as f:
>     TypeError: 'encoding' is an invalid keyword argument for this function
> 
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hc/jf7tmyyn3fq_8d7l7m_fm09c0000gn/T/pip-build-s3mE1w/cryptocompare/

**Comment by lagerfeuer** [comment]
can you try with pip3? it seems like this error occurs because pip is using python 2, the package is python 3.

**Comment by Metaphor31** [comment]
Hi, 

I would like advice to build the same function but to get all history of data (Close, dates, volume) between two dates :)

Could you please help me ? thanks

def get_historical_price(coin, curr=CURR, timestamp=time.time()):
    if isinstance(timestamp, datetime.datetime):
        timestamp = time.mktime(timestamp.timetuple())
    return query_cryptocompare(URL_HIST_PRICE.format(coin, format_parameter(curr), int(timestamp)))
