### ISSUE TITLE
Add parameter 'e' (exchange) to method get_historical_price()

### ISSUE THREAD

**Issue by sebastianhaberey** [lagerfeuer/cryptocompare#13]
First off, thanks for this convenient library 👍 

If I had one wish it would be to add the parameter 'e' to the method get_historical_price(). It is mentioned on the [cryptocompare.com website](https://min-api.cryptocompare.com/) and enables the caller to select a specific exchange as source for the historical price instead of the default cryptocompare.com aggregate CCCAGG.

**Comment by lagerfeuer** [comment]
Thank you for your input, this is now added with 9ccc78177a45caa22fc0b46ee393d0fd8dbb134b.
If you want more features, feel free to add them yourself and open a pull request or open another issue, bigger changes might take a while because of my class load.
