### ISSUE TITLE
How to just get the current price?

### ISSUE THREAD

**Issue by saikrishna-1996** [lagerfeuer/cryptocompare#17]
coin_price = (cryptocompare.get_price(coin,curr='USD',full=False))
dictlist = list(coin_price.values())
print(dictlist[0])

This gives us "{'USD': 0.06061}". Is it possible to just get the numerical value (0.06061) instead of getting the whole string "{'USD': 0.06061}"? This would be useful in further computations

**Comment by saikrishna-1996** [comment]
I did this, and it's working:

dictlist = list(coin_price.values())
nums =  (re.findall('\d+', str(dictlist[0]) ))
if(len(nums) == 1):
	nums.append('0')
nums[0] = float(nums[0])
len_nums1 = len(nums[1])
nums[1] = float(nums[1])/10.0**float(len_nums1)
price = nums[0] + nums[1]
print(price)

But, may be there is a better way to do this?

**Comment by 2martin2** [comment]
yes there is.
the return value of get_price (coin_price in your example) is a dict in a dict. 
So you could just use .values() again to get the value of the second dict but I would suggest:
price = coin_price['coin']['USD']

**Comment by lagerfeuer** [comment]
@2martin2 thank you for answering this question :+1:
