### ISSUE TITLE
can not  get coin lidz

### ISSUE THREAD

**Issue by goerstn** [lagerfeuer/cryptocompare#19]
Hi,
suddenly i cant retrieve coin info no more. It throws this error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "..\cryptocompare.py", line 52, in get_coin_list
    response = query_cryptocompare(URL_COIN_LIST, False)['Data']
TypeError: 'NoneType' object is not subscriptable
Error getting coin information. Expecting value: line 1 column 1 (char 0)
```

I am new to coding, so i dont know if thats really an issue of crypto compare, but i tried in a fresh console and i got same error. Maybe could some look into it.

**Comment by lagerfeuer** [comment]
@goerstn hey, sorry for the late response.
Are you sure you have a connection to the internet? I just tried it and it worked.
Also, how are you using the library and what version are you on?

**Comment by lagerfeuer** [comment]
Closing, because it seems to be an unrelated issue (e.g. network problems).
