### ISSUE TITLE
Calling from Windows WSL Ubuntu strips out response info from JSON

### ISSUE THREAD

**Issue by maxrottersman** [lagerfeuer/cryptocompare#31]
To do some testing on my local windows machine I want to update a SQLite database with an API call to Cryptocompare. However, I get different JSON back in Ubuntu (WSL) than I get back in Windows. Weird! This becomes a problem later when I parse the JSON into SQLite. To make matters even stranger, this works fine on my Ubuntu VM instance on Google Cloud.

In Ubuntu in Windows WS I run this and get this:
res = cryptocompare.get_historical_price_minute('BTC', curr='USD',limit=1) print(res)
[{'time': 1580058960, 'close': 8561, 'high': 8569.55, 'low': 8561, 'open': 8565.61, 'volumefrom': 35.27, 'volumeto': 302097.78}, {'time': 1580059020, 'close': 8554.96, 'high': 8561, 'low': 8554.96, 'open': 8561, 'volumefrom': 0, 'volumeto': 0}]

Under Windows Python I get this:
res = cryptocompare.get_historical_price_minute('BTC', curr='USD',limit=1)
>>> print(res)
{'Response': 'Success', 'Type': 100, 'Aggregated': False, 'Data': [{'time': 1580059800, 'close': 8564.72, 'high': 8565.85, 'low': 8561.4, 'open': 8561.4, 'volumefrom': 9.249, 'volumeto': 79165.7}, {'time': 1580059860, 'close': 8564.51, 'high': 8564.72, 'low': 8564.51, 'open': 8564.72, 'volumefrom': 0, 'volumeto': 0}], 'TimeTo': 1580059860, 'TimeFrom': 1580059800, 'FirstValueInArray': True, 'ConversionType': {'type': 'direct', 'conversionSymbol': ''}, 'RateLimit': {}, 'HasWarning': False}

**Comment by lagerfeuer** [comment]
This is really weird. Are you on the latest version? If not, what version are you running?
What is your exact setup?
And can you post the entire code you are using to fetch the price?

Unfortunately, I don't work on windows. But I am going to try to fix this.

**Comment by maxrottersman** [comment]
Hi.  I don't think this is a problem worth fixing until you get another complaint.  It may be a one-off oddity of Windows WSL.  I came up with another solution for what I need.  Thanks for your offering to fix!

**Comment by lagerfeuer** [comment]
@maxrottersman alright, thank you for opening an issue though. I'll leave this closed in the meantime.
