### ISSUE TITLE
Add exchange to get_historical_price (minute, hour, and day)

### ISSUE THREAD

**Issue by GiliR4t1qbit** [lagerfeuer/cryptocompare#33]
In the cryptocompare API, it's possible to pass the exchange via the e argument to get_historical_price_minute (hour and day), but not currently through this package. This addition needs to be made to each of those three functions, to the tests, and to the README. 

I've made the (pretty straightforward) changes in this Pull Request: #32

**Comment by GiliR4t1qbit** [comment]
@lagerfeuer: The build failed due to failing to "Upload coverage report to coveralls.io". I can see that the tests passed, and they pass on my machine as well.

**Comment by lagerfeuer** [comment]
@GiliR4t1qbit Thank you for your contribution, I have merged this. And yes, the Upload step fails, I need to fix this in regards to Pull Requests.
