### ISSUE TITLE
Passing API keys

### ISSUE THREAD

**Issue by carmelotony** [lagerfeuer/cryptocompare#39]
Is there a way to pass CryptoCompare API keys to pull down more data?

**Comment by lagerfeuer** [comment]
Sorry for the late response. No, there is no way to do that currently. I've had it on my radar for a while, but since I don't really use this library anymore, I haven't had the need to update it. Feel free to open a pull request if you have the time, I'd gladly merge it.

**Comment by carmelotony** [comment]
No Worries. Thanks for setting this up. I was able to pull the historic data I need over a few days. If I end up using higher frequency data, I'll look into adding a paid API key. Thanks again, this was really useful.

**Comment by lagerfeuer** [comment]
@carmelotony This was addressed in #40, take a look if that's what you need! Going to release it later today. Closing this issue.
