### ISSUE TITLE
Hourly Data Support?

### ISSUE THREAD

**Issue by vikramarun** [lagerfeuer/cryptocompare#4]
Hey guys, just wanted to say that I really appreciate the work. Glad someone was able to get the API working in Python. Was wondering if you would be able to add in an API function for hourly historical data? Its already a function provided by Cryptocompare (HistoHour). Thanks.

**Comment by lagerfeuer** [comment]
added it with abf36b54a06beb63abb65ad7a8fa96cd2e79b244

**Comment by vertangelx** [comment]
Awesome! Can it use the `toTs` parameter, so that it fetches the max limit of 2000 bars until the `toTs` timestamp?

**Comment by lagerfeuer** [comment]
@vertangelx not yet, feel free to open a pull request. If you don't want to do it, I will add it when I have time (could take a while).

**Comment by lagerfeuer** [comment]
no answer, closing.
