### ISSUE TITLE
Argument was changed in get_price() and documentation is outdated

### ISSUE THREAD

**Issue by evprkr** [lagerfeuer/cryptocompare#43]
Both here and on PyPi, the documentation says to use the `curr` argument to set currency, but I found some of my old code not working, checked the latest updates, and it looks like `curr` has been changed to `currency`, with no changes in documentation.

**Comment by lagerfeuer** [comment]
Yes, you are right. Very sorry about that, forgot to fix the docs. On it right now.

**Comment by lagerfeuer** [comment]
Fixed in v0.7.5, thanks for pointing this out!

**Comment by evprkr** [comment]
Great! Thanks for fixing that so fast. Excellent work on the module too, I love it.
