### ISSUE TITLE
Constantly getting an error You are over your rate limit please upgrade your account!

### ISSUE THREAD

**Issue by senovr** [lagerfeuer/cryptocompare#44]
Hi, 
1. I have installed latest version of cryptocompare via pip.
2. I have registered and created an API key at cryptocompare (checked the following options)
![image](https://user-images.githubusercontent.com/20754344/108666175-1dcc0f00-7509-11eb-86a0-b3e302ad406d.png)
3. I have tested freshly created API key @ cryptocompare website, getting response without problems.
4. I placed API key to .env file 
5. In my jupyter notebook, I tried the following:
```
import cryptocompare as cr
from dotenv import load_dotenv # add this line for api key loading
import os
load_dotenv()
apikey=os.getenv('API_KEY')
(api key loaded successfully, the same as created).
# setting the key for cryptocompare library
cr.cryptocompare._set_api_key_parameter(apikey)
# response is ok, '&api_key=xxx(my api key here)'
```
but, when I am trying:
`btc=cr.get_historical_price_day('BTC', currency='USD', limit=30)`

I constantly get an error that I am over my rate limit.

Can you please direct me what I am doing wrong?

**Comment by senovr** [comment]
After some investigation (btw, I am on Windows 10 and using anaconda):
1. Created CRYPTOCOMPARE_API_KEY = api key. - still not working.

What works for me:
first, temporarily set environmental key with 
`os.environ['CRYPTOCOMPARE_API_KEY'] = 'xxx(my API key here)'`
after that,  get_historical_price function started to work as expected.

**Comment by lagerfeuer** [comment]
How are you invoking your script, i.e. how are you setting the environment variable before your script runs?
I don't use Windows, but I am guessing the problem is within the actual environment.

**Comment by senovr** [comment]
As I mentioned above, I tried three approaches:

First is load API key from .env file  to variable apikey,
```
from dotenv import load_dotenv # add this line for api key loading
import os
load_dotenv()
apikey=os.getenv('API_KEY')
```
and using 
`cryptocompare.cryptocompare._set_api_key_parameter(apikey)`
Trying to get some data with 
`btc=cryptocompare.get_historical_price_day('BTC', currency='USD', limit=30)`
it raises an error.

The second is Windows-specific:
I created the CRYPTOCOMPARE_API_KEY  variable in Windows
![image](https://user-images.githubusercontent.com/20754344/108716315-8689aa80-754e-11eb-8c8d-cf32cc7c87a1.png)
After that, invoke `.get_hourly_data` (without invoking `_set_api_key_parameter`) - as it supposed to catch  the API key from CRYPTOCOMPARE_API_KEY  
Still raises an error 

The third approach that worked (no error, data are downloading):
Load API key from .env file, place it in apikey variable.
Execute 
`os.environ['CRYPTOCOMPARE_API_KEY'] = apikey`


After that, invoke `.get_hourly_data` (without envoking `_set_api_key_parameter`)

**Comment by lagerfeuer** [comment]
Mhmm, I don't have a Windows machine in use right now. And I don't use Windows to program ever. I will set up a VM when I get a chance and look into it. I'll leave this issue open in the meantime.

**Comment by lagerfeuer** [comment]
Stale issue at this point, closing.
