### ISSUE TITLE
get_average does not work

### ISSUE THREAD

**Issue by lagerfeuer** [lagerfeuer/cryptocompare#6]
get_avg (generateAvg on CryptoCompare) does not work anymore, not even the examples provided by CryptoCompare. They exit with error: "e param seems to be missing."

**Comment by beauzeph** [comment]
I noticed the same issue here, using python3

**Comment by lagerfeuer** [comment]
@beauzeph it seems to be an internal issue, given that this [example](https://min-api.cryptocompare.com/data/generateAvg?fsym=BTC&tsym=USD&markets=Coinbase,Bitfinex) from CryptoCompare does not work either. or a possibly outdated documentation [here](https://www.cryptocompare.com/api/).

**Comment by lagerfeuer** [comment]
fixed with #7
